### ISSUE TITLE
Mod Loading Failed

### ISSUE THREAD

**Issue by Mockingjason** [paulevsGitch/BetterEnd#112]
I am able to generate worlds with this mod normally in singeplayer. Even if I copy-paste a world I normally generated with this mod without any errors, once I try to host it on server.pro (with some other mods), I get this error:

---- Minecraft Crash Report ----

// Would you like a cupcake?

Time: 3/8/21, 3:18 PM

Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed

at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[?:?] {re:classloading}

at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[?:?] {re:classloading}

at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}

at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}

at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}

at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}

at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}

at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.4-35.1.4.jar:35.1] {}

at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}

at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}

at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}

at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}

at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.4-35.1.4.jar:?] {}

at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.4-35.1.4.jar:?] {}

at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.4-35.1.4.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:

---------------------------------------------------------------------------------------

-- Head --

Thread: main

Stacktrace:

at java.lang.ClassLoader.findClass(Unknown Source) ~[?:?] {}

-- MOD betterendforge --

Details:

Caused by 0: java.lang.TypeNotPresentException: Type net.minecraftforge.common.world.ForgeWorldType not present

at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(Unknown Source) ~[?:?] {}

at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Unknown Source) ~[?:?] {}

at sun.reflect.generics.tree.ClassTypeSignature.accept(Unknown Source) ~[?:?] {}

at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Unknown Source) ~[?:?] {}

at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Unknown Source) ~[?:?] {}

at sun.reflect.generics.tree.ClassTypeSignature.accept(Unknown Source) ~[?:?] {}

at sun.reflect.generics.repository.ConstructorRepository.computeParameterTypes(Unknown Source) ~[?:?] {}

at sun.reflect.generics.repository.ConstructorRepository.getParameterTypes(Unknown Source) ~[?:?] {}

at java.lang.reflect.Executable.getGenericParameterTypes(Unknown Source) ~[?:?] {}

at java.lang.reflect.Method.getGenericParameterTypes(Unknown Source) ~[?:?] {}

at net.minecraftforge.eventbus.ASMEventHandler.<init>(ASMEventHandler.java:55) ~[eventbus-3.0.5-service.jar:?] {}

at net.minecraftforge.eventbus.EventBus.register(EventBus.java:254) ~[eventbus-3.0.5-service.jar:?] {}

at net.minecraftforge.eventbus.EventBus.registerListener(EventBus.java:150) ~[eventbus-3.0.5-service.jar:?] {}

at net.minecraftforge.eventbus.EventBus.lambda$registerClass$2(EventBus.java:78) ~[eventbus-3.0.5-service.jar:?] {}

at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?] {}

at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?] {}

at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?] {}

at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:?] {}

at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?] {}

at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?] {}

at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?] {}

at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?] {}

at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?] {}

at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?] {}

at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:78) ~[eventbus-3.0.5-service.jar:?] {}

at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-3.0.5-service.jar:?] {}

at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[?:?] {re:classloading}

at java.util.ArrayList.forEach(Unknown Source) ~[?:?] {}

at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[?:?] {re:classloading}

at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[?:35.1] {re:classloading}

at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[?:?] {re:classloading}

at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}

at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}

at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}

at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}

at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}

at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}

at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}

Mod File: betterendforge-1.16.4-1.4.1.jar

Failure message: BetterEnd Forge (betterendforge) has failed to load correctly

java.lang.TypeNotPresentException: Type net.minecraftforge.common.world.ForgeWorldType not present

Mod Version: 1.16.4-1.4.1

Mod Issue URL: https://github.com/Beethoven92/BetterEndForge/issues

Exception message: java.lang.ClassNotFoundException: net.minecraftforge.common.world.ForgeWorldType

Stacktrace:

at java.lang.ClassLoader.findClass(Unknown Source) ~[?:?] {}

at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}

at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.6.jar:?] {re:classloading}

at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}

at java.lang.Class.forName0(Native Method) ~[?:?] {}

at java.lang.Class.forName(Unknown Source) ~[?:?] {}

at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(Unknown Source) ~[?:?] {}

at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Unknown Source) ~[?:?] {}

at sun.reflect.generics.tree.ClassTypeSignature.accept(Unknown Source) ~[?:?] {}

at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Unknown Source) ~[?:?] {}

at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Unknown Source) ~[?:?] {}

at sun.reflect.generics.tree.ClassTypeSignature.accept(Unknown Source) ~[?:?] {}

at sun.reflect.generics.repository.ConstructorRepository.computeParameterTypes(Unknown Source) ~[?:?] {}

at sun.reflect.generics.repository.ConstructorRepository.getParameterTypes(Unknown Source) ~[?:?] {}

at java.lang.reflect.Executable.getGenericParameterTypes(Unknown Source) ~[?:?] {}

at java.lang.reflect.Method.getGenericParameterTypes(Unknown Source) ~[?:?] {}

at net.minecraftforge.eventbus.ASMEventHandler.<init>(ASMEventHandler.java:55) ~[eventbus-3.0.5-service.jar:?] {}

at net.minecraftforge.eventbus.EventBus.register(EventBus.java:254) ~[eventbus-3.0.5-service.jar:?] {}

at net.minecraftforge.eventbus.EventBus.registerListener(EventBus.java:150) ~[eventbus-3.0.5-service.jar:?] {}

at net.minecraftforge.eventbus.EventBus.lambda$registerClass$2(EventBus.java:78) ~[eventbus-3.0.5-service.jar:?] {}

at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?] {}

at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?] {}

at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?] {}

at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:?] {}

at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?] {}

at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?] {}

at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?] {}

at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?] {}

at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?] {}

at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?] {}

at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:78) ~[eventbus-3.0.5-service.jar:?] {}

at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-3.0.5-service.jar:?] {}

at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[?:?] {re:classloading}

at java.util.ArrayList.forEach(Unknown Source) ~[?:?] {}

at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[?:?] {re:classloading}

at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[?:35.1] {re:classloading}

at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[?:?] {re:classloading}

at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}

at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}

at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}

at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}

at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}

at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}

at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}

-- System Details --

Details:

Minecraft Version: 1.16.4

Minecraft Version ID: 1.16.4

Operating System: Linux (amd64) version 4.15.0-106-generic

Java Version: 11, Oracle Corporation

Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation

Memory: 922746880 bytes (880 MB) / 1655701504 bytes (1579 MB) up to 5368709120 bytes (5120 MB)

CPUs: 3

JVM Flags: 3 total; -Xms1024M -Xmx5120M -XX:-UsePerfData

ModLauncher: 8.0.6+85+master.325de55

ModLauncher launch target: fmlserver

ModLauncher naming: srg

ModLauncher services:

/mixin-0.8.2.jar mixin PLUGINSERVICE

/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE

/forge-1.16.4-35.1.4.jar object_holder_definalize PLUGINSERVICE

/forge-1.16.4-35.1.4.jar runtime_enum_extender PLUGINSERVICE

/forge-1.16.4-35.1.4.jar capability_inject_definalize PLUGINSERVICE

/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE

/forge-1.16.4-35.1.4.jar runtimedistcleaner PLUGINSERVICE

/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE

/forge-1.16.4-35.1.4.jar fml TRANSFORMATIONSERVICE

FML: 35.1

Forge: net.minecraftforge:35.1.4

FML Language Providers:

javafml@35.1

minecraft@1

Mod List:

forge-1.16.4-35.1.4-server.jar |Minecraft |minecraft |1.16.4 |CREATE_REG|NOSIGNATURE

YungsApi-1.16.4-Forge-3.jar |YUNG's API |yungsapi |1.16.4-Forge-3 |CREATE_REG|NOSIGNATURE

voicechat-1.16.4-1.1.1.jar |Simple Voice Chat |voicechat |1.16.4-1.1.1 |CREATE_REG|NOSIGNATURE

The-Abyss-Chapter-2-Mod-1.16.5.jar |TheAbyss |theabyss |1.0.6-8 |CREATE_REG|NOSIGNATURE

BiomesOPlenty-1.16.4-13.0.0.421-universal.jar |Biomes O' Plenty |biomesoplenty |1.16.4-13.0.0.418 |CREATE_REG|NOSIGNATURE

furniture-7.0.0-pre19-1.16.3.jar |MrCrayfish's Furniture Mod |cfm |7.0.0-pre19 |CREATE_REG|NOSIGNATURE

dungeons_plus-1.16.4-1.1.3.jar |Dungeons Plus |dungeons_plus |1.1.3 |CREATE_REG|NOSIGNATURE

jei-1.16.4-7.6.1.66.jar |Just Enough Items |jei |7.6.1.66 |CREATE_REG|NOSIGNATURE

AttributeFix-1.16.4-9.0.2.jar |AttributeFix |attributefix |9.0.2 |CREATE_REG|ea:45:b3:82:b6:9d::e7:2e:34:e1:92:d5:b4:9b:69:90:d3:4f:2e:71:99:b0:be:40:80:27:1f:3e:b0

immersive-portals-0.16-mc1.16.5-forge.jar |Immersive Portals |immersive_portals |0.14 |CREATE_REG|NOSIGNATURE

forge-1.16.4-35.1.4-universal.jar |Forge |forge |35.1.4 |CREATE_REG|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4::39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90

Patchouli-1.16.4-50.jar |Patchouli |patchouli |1.16.4-50 |CREATE_REG|NOSIGNATURE

overloadedarmorbar-5.1.0.jar |Overloaded Armor Bar |overloadedarmorbar |5.1.0 |CREATE_REG|NOSIGNATURE

BetterMineshafts-Forge-1.16.3-1.1.1.jar |YUNG's Better Mineshafts |bettermineshafts |1.16.3-1.1.1 |CREATE_REG|NOSIGNATURE

BetterCaves-Forge-1.16.4-1.1.jar |YUNG's Better Caves |bettercaves |1.16.4-1.1 |CREATE_REG|NOSIGNATURE

[ERROR] betterendforge-1.16.4-1.4.1.jar |BetterEnd Forge |betterendforge |1.16.4-1.4.1 |ERROR |NOSIGNATURE

structure_gel-1.16.4-1.7.5.jar |Structure Gel API |structure_gel |1.7.5 |CREATE_REG|NOSIGNATURE

journeymap-1.16.5-5.7.1.jar |Journeymap |journeymap |5.7.1 |CREATE_REG|NOSIGNATURE

DungeonsMod-1.16.3-1.2.23.jar |Dungeons Arise |dungeons_arise |1.2.056 |CREATE_REG|NOSIGNATURE

citadel-1.5.3.jar |Citadel |citadel |1.5.3 |CREATE_REG|NOSIGNATURE

Alexs-Mob-Mod-1.16.4.jar |Alex's Mobs |alexsmobs |1.4.0 |CREATE_REG|NOSIGNATURE

iceandfire-2.1.5-1.16.4.jar |Ice and Fire |iceandfire |2.1.5-1.16.4 |CREATE_REG|NOSIGNATURE

Crash Report UUID: 28c3f0c5-c6c6-462e-8483-ad487496a1d8 [main/FATAL] [minecraft/Main]: Failed to start the minecraft server

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [

BetterEnd Forge (betterendforge) has failed to load correctly

§7java.lang.TypeNotPresentException: Type net.minecraftforge.common.world.ForgeWorldType not present

]

at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:263) ~[?:?] {re:classloading}

at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230) ~[?:?] {re:classloading}

at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:188) ~[?:?] {re:classloading}

at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[?:?] {re:classloading}

at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}

at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}

at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}

at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}

at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}

at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.4-35.1.4.jar:35.1] {}

at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}

at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}

at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}

at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}

at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.4-35.1.4.jar:?] {}

at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.4-35.1.4.jar:?] {}

at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.4-35.1.4.jar:?] {}

**Comment by paulevsGitch** [comment]
This is a Fabric mod tracker

**Comment by Beethoven92** [comment]
Yeah, you should have reported this to BetterEnd (Forge) [https://github.com/Beethoven92/BetterEndForge/issues](url)
Anyway, you just have to upgrade your Forge version..and possibly your BetterEnd version, you are using 1.4.1, but we are actually on 1.5.1
