### ISSUE TITLE
Crash on fabric-server clean start up on 0.97-0.98

### ISSUE THREAD

**Issue by x-sis** [paulevsGitch/BetterEnd#209]
Hello!

On better-end 0.97-0.98, which were released recently, i have this crash on start up (the same on the clean server without old map or the other mods);

[16:11:03] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'betterend'!
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:33) ~[fabric-server-launch.jar:?]
        at net.minecraft.server.Main.main(Main.java:92) [intermediary-hamster_server.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-launch.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_1100
        at ru.betterend.registry.EndBlocks.<clinit>(EndBlocks.java:53) ~[better-end-0.9.8-pre.jar:?]
        at ru.betterend.registry.EndBlockEntities.<clinit>(EndBlockEntities.java:17) ~[better-end-0.9.8-pre.jar:?]
        at ru.betterend.BetterEnd.onInitialize(BetterEnd.java:42) ~[better-end-0.9.8-pre.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-server-launch.jar:?]
        ... 17 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1100
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_291]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_291]
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_291]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_291]
        at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:57) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_291]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_291]
        at ru.betterend.registry.EndBlocks.<clinit>(EndBlocks.java:53) ~[better-end-0.9.8-pre.jar:?]
        at ru.betterend.registry.EndBlockEntities.<clinit>(EndBlockEntities.java:17) ~[better-end-0.9.8-pre.jar:?]
        at ru.betterend.BetterEnd.onInitialize(BetterEnd.java:42) ~[better-end-0.9.8-pre.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-server-launch.jar:?]
        ... 17 more

**Comment by paulevsGitch** [comment]
Looks like there is some parts of client code, we will fix it

**Comment by x-sis** [comment]
I can confirm it was fixed. Thank you!

**Comment by paulevsGitch** [comment]
Fixed in 0.9.8.1
