### ISSUE TITLE
3rd party mod integrations rely on load order

### ISSUE THREAD

**Issue by sfPlayer1** [paulevsGitch/BetterEnd#219]
better-end-0.9.1-pre from a slightly dated ATM3 copy is sensitive to the mod load order: if byg loads after better-end, it crashes as follows:
```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'betterend'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:34)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:67)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.ExceptionInInitializerError
	at ru.betterend.integration.byg.BYGIntegration.register(BYGIntegration.java:29)
	at ru.betterend.integration.Integrations.lambda$register$0(Integrations.java:19)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at ru.betterend.integration.Integrations.register(Integrations.java:17)
	at ru.betterend.BetterEnd.onInitialize(BetterEnd.java:63)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:46)
	... 11 more
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1959.method_24377()" because "biome" is null
	at ru.betterend.integration.byg.biomes.OldBulbisGardens.makeDef(OldBulbisGardens.java:33)
	at ru.betterend.integration.byg.biomes.OldBulbisGardens.<init>(OldBulbisGardens.java:28)
	at ru.betterend.integration.byg.biomes.BYGBiomes.<clinit>(BYGBiomes.java:9)
	... 17 more
```
Both byg's biome initialization and better-end's access to byg biomes run off the main entry point. In the above crash better-end runs first, so the biome `bulbis_gardens` is missing.

Fabric Loader doesn't give any guarantees on the entry point execution order, mods need to ensure proper execution order through registration events, custom entrypoints or other means.

**Comment by paulevsGitch** [comment]
0.9.1 is outdated mod version, current code is very different from it
