### ISSUE TITLE
Replacing Overworld Crashes

### ISSUE THREAD

**Issue by CaptainAdams** [paulevsGitch/BetterEnd#251]
If you change the "replace overworld with end" in the generator config it will crash the game when loading a single player world, or a server whenever someone joins it.

**Comment by paulevsGitch** [comment]
Can you please send your logs?

**Comment by CaptainAdams** [comment]
I have no clue how to do this. Does this work?
`[21:50:57] [Server thread/INFO]: Starting minecraft server version 1.17
[21:50:57] [Server thread/INFO]: Loading properties
[21:50:57] [Server thread/INFO]: Default game type: SURVIVAL
[21:50:57] [Server thread/INFO]: Generating keypair
[21:50:57] [Server thread/INFO]: Starting Minecraft server on *:25565
[21:50:57] [Server thread/INFO]: Using default channel type
[21:50:58] [Server thread/INFO]: Preparing level "nolol"
[21:50:58] [Server thread/WARN]: Unable to find spawn biome
[21:50:59] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[21:50:59] [Worker-Main-10/INFO]: Preparing spawn area: 0%
[21:51:00] [Worker-Main-13/INFO]: Preparing spawn area: 0%
[21:51:00] [Worker-Main-10/INFO]: Preparing spawn area: 0%
[21:51:00] [Worker-Main-10/INFO]: Preparing spawn area: 8%
[21:51:01] [Worker-Main-13/INFO]: Preparing spawn area: 69%
[21:51:01] [Server thread/INFO]: Time elapsed: 2218 ms
[21:51:01] [Server thread/INFO]: Done (3.315s)! For help, type "help"
[21:51:14] [User Authenticator #1/INFO]: UUID of player Captain_Adams is d3e8acd2-69aa-4c6a-b030-74f0661aaef1
[21:51:14] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'java.util.Optional net.minecraft.class_3312.method_14512(java.util.UUID)'
	at net.minecraft.class_3324.handler$zpn000$be_placeNewPlayer(class_3324.java:2995) ~[intermediary-server.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java) ~[intermediary-server.jar:?]
	at net.minecraft.class_3248.method_33800(class_3248.java:129) ~[intermediary-server.jar:?]
	at net.minecraft.class_3248.method_14384(class_3248.java:117) ~[intermediary-server.jar:?]
	at net.minecraft.class_3248.redirect$bdg000$handlePlayerJoin(class_3248.java:563) ~[intermediary-server.jar:?]
	at net.minecraft.class_3248.method_18785(class_3248.java:67) ~[intermediary-server.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:234) ~[intermediary-server.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:904) ~[intermediary-server.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:334) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:833) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:692) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[21:51:15] [Server thread/ERROR]: This crash report has been saved to: E:\Server\End_Server\.\crash-reports\crash-2021-07-19_21.51.15-server.txt
[21:51:15] [Server thread/INFO]: Stopping server
[21:51:15] [Server thread/INFO]: Saving players
[21:51:15] [Server thread/INFO]: Saving worlds
[21:51:15] [Server thread/INFO]: Saving chunks for level 'ServerLevel[nolol]'/minecraft:overworld
[21:51:15] [Server thread/INFO]: Saving local markers data to NBT
[21:51:15] [Server thread/INFO]: ThreadedAnvilChunkStorage (nolol): All chunks are saved
[21:51:15] [Server thread/INFO]: Saving chunks for level 'ServerLevel[nolol]'/minecraft:the_nether
[21:51:15] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[21:51:15] [Server thread/INFO]: Saving chunks for level 'ServerLevel[nolol]'/minecraft:the_end
[21:51:16] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[21:51:16] [Server thread/INFO]: ThreadedAnvilChunkStorage (nolol): All chunks are saved
[21:51:16] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[21:51:16] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved`

**Comment by CaptainAdams** [comment]
It only crashes when swapOverworldToEnd is set to true

**Comment by paulevsGitch** [comment]
Thank you, now I see this issue clear. I think I will remove this feature at all as it causes issues with other mods, I can recommend you to try [this mod](https://www.curseforge.com/minecraft/mc-mods/globalspawn) to set your spawn in the End

**Comment by CaptainAdams** [comment]
Thanks for the recommendation!

**Comment by paulevsGitch** [comment]
Tried this in the latest version, works fine, probably it was fixed during other fixes

**Comment by paulevsGitch** [comment]
Respawning always is on zero coordinates, probably this feature will be completely removed due to different incompatibilities

**Comment by paulevsGitch** [comment]
Tested in 1.17.1, everything works fine, looks like I just forgot to close this issue
