### ISSUE TITLE
Crashes when generating outer islands with the Simply Improved Terrain mod installed

### ISSUE THREAD

**Issue by gniftygnome** [paulevsGitch/BetterEnd#277]
This has already been filed by someone else with Simply Improved Terrain:  https://github.com/KdotJPG/Simply-Improved-Terrain/issues/17
I assume Simply Improved Terrain (an awesome mod IMO) is violating some unwritten contract in the vanilla code.

However, the stack trace only mentions Better End, which led me to spend the time to bisect a large mod pack I'm working on for this bug.  So I am filing an issue on Better End in the hopes it might save somebody else the same effort I just made.

The central end island occasionally generates fine.  If not, or when generating the outer islands the game crashes.  The crash looks like this (full crash log attached):

Caused by: java.lang.NullPointerException: Cannot invoke "java.util.OptionalInt.orElse(int)" because the return value of "net.minecraft.class_3754.method_26263(int, int, net.minecraft.class_2680[], java.util.function.Predicate, int, int)" is null
	at net.minecraft.world.gen.chunk.NoiseChunkGenerator.getHeight(NoiseChunkGenerator:193) ~[?:?]
	at ru.betterend.world.structures.features.EternalPortalStructure.isFeatureChunk(EternalPortalStructure.java:35) ~[better-end-0.10.5-pre.jar:?]
	at ru.betterend.world.structures.features.EternalPortalStructure.shouldStartAt(EternalPortalStructure.java:24) ~[better-end-0.10.5-pre.jar:?]
	at net.minecraft.world.gen.feature.StructureFeature.tryPlaceStart(StructureFeature:266) ~[?:?]

[crash-2021-08-09_17.36.54-server.txt](https://github.com/paulevsGitch/BetterEnd/files/6958168/crash-2021-08-09_17.36.54-server.txt)

**Comment by paulevsGitch** [comment]
Hi, the reason can be [here](https://github.com/KdotJPG/Simply-Improved-Terrain/blob/Fabric-1.17/src/main/java/jpg/k/simplyimprovedterrain/mixin/MixinNoiseChunkGenerator.java#L171). As this is CallbackInfoReturnable on HEAD - it will replace sampleHeightmap, and if all conditions in cycle fail - cir.cancel() will set function return value to null. As a result you will get NullPointerException in features on heightmap sampling, which you can see in your logs.

Proper solution will be replace cir.cancel() with cir.setReturnValue(OptionalInt.of(0)) in Simply Improved Terrain

**Comment by paulevsGitch** [comment]
This problem happened in the End as there is void between islands and heightmap values can be zero

**Comment by paulevsGitch** [comment]
As this is external issue I’m closing this

**Comment by gniftygnome** [comment]
Thanks.  This appears to be fixed in Simply Improved Terrain 0.4.0.3.
