### ISSUE TITLE
Better End and Better Nether crashing game

### ISSUE THREAD

**Issue by SilentBloody** [paulevsGitch/BetterEnd#340]
I'm trying to use the mods and i have all the requirements. I've installed bclib and already have fabric api, but when i launch my game it ended up crashing. Before everything was working just fine

Note: I have both Better End and Better Nether installed. I tried doing 1 of them but its the same result, It crashed.

This is the Crash report:
---- Minecraft Crash Report ----
// There are four lights!

Time: 11/4/21, 6:42 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'betternether'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:457)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.ExceptionInInitializerError
	at paulevs.betternether.BetterNether.onInitialize(BetterNether.java:26)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more
Caused by: java.lang.IllegalStateException: Tag minecraft:shulker_boxes used before it was bound
	at net.minecraft.class_5120$class_5121.method_26776(class_5120.java:84)
	at net.minecraft.class_5120$class_5121.method_15141(class_5120.java:95)
	at net.minecraft.class_4970$class_4971.method_26164(class_4970.java:983)
	at net.minecraft.class_2248.handler$bpc000$getSoundGroup(class_2248.java:2656)
	at net.minecraft.class_2248.method_9573(class_2248.java)
	at paulevs.betternether.recipes.RecipesHelper.makeStairsRecipe(RecipesHelper.java:44)
	at paulevs.betternether.registry.BlocksRegistry.registerStairs(BlocksRegistry.java:551)
	at paulevs.betternether.registry.BlocksRegistry.<clinit>(BlocksRegistry.java:39)
	... 13 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:457)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

**Comment by quiqueck** [comment]
Hm, this actually looks like an issue with BetterNether.

Could you please give us the following info:
 - Versions for BCLib, FabricAPI, BetterNether, BetterEnd and the FabricLoader.
 - Do you have any other Mods/Datapacks installed?

**Comment by SilentBloody** [comment]
> Hm, this actually looks like an issue with BetterNether.
> 
> 
> 
> Could you please give us the following info:
> 
>  - Versions for BCLib, FabricAPI, BetterNether, BetterEnd and the FabricLoader.
> 
>  - Do you have any other Mods/Datapacks installed?

I have Fabic and Bclib at the latest version. I have other mods installed

**Comment by paulevsGitch** [comment]
"latest" is not a version, we are asking about your version numbers

**Comment by SilentBloody** [comment]
> "latest" is not a version, we are asking about your version numbers
bclib-0.4.4-1.17.1
[1.17.1] Fabric API 0.42.0
I have other mods with it but im not sure how to send it through github

**Comment by quiqueck** [comment]
Could you maybe upload your log file to something like https://pastebin.com and send us the link?

**Comment by SilentBloody** [comment]
> Could you maybe upload your log file to something like https://pastebin.com and send us the link?

https://pastebin.com/F9KbX4Sg

Note I know ender scape was interfering with the better end mod but the game wont launch even when i removed the ender scape mod.

**Comment by quiqueck** [comment]
Thanks for reporting back to us. :)

**Comment by BeckPhillips** [comment]
For futureproofing, could you maybe post _why_ you've marked this as completed, or at least a theorized fix? I'm having a similar issue on my own server ;-;

**Comment by paulevsGitch** [comment]
> why you've marked this as completed

If you will read last messages you will see why. Anyway, asking thing in issue solved 4 years ago in an old repo is a bad idea in general
