### ISSUE TITLE
java.lang.ClassCastException: class ru.betterend.blocks.MossyGlowshroomCapBlock cannot be cast to class net.minecraft.class_2185

### ISSUE THREAD

**Issue by davidalb97** [paulevsGitch/BetterEnd#345]
A stacktrace error appeared on the console when pregenerating the end dimension with fabric chunk pregenerator.

**How to replicate:**
- Install bclib@0.5.1, betterend@0.12.2, chunkpregen@0.3.3, fabric@0.42.1+1.17, fabricloader@0.11.7
- Start pregenerating with the command: `execute in the_end run pregen start 19999`

**Error:**
```
[Worker-Main-13/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[Worker-Main-13/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[Worker-Main-2/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[Worker-Main-2/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[Worker-Main-2/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[Worker-Main-2/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[Worker-Main-2/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[Server thread/WARN]: Tried to load a DUMMY block entity @ class_2338{x=2312, y=78, z=-1223} but found not block entity block Block{minecraft:end_stone} at location
[Server thread/WARN]: Tried to load a block entity for block Block{minecraft:end_stone} but failed at location class_2338{x=2312, y=78, z=-1223}
[Server thread/WARN]: Tried to load a DUMMY block entity @ class_2338{x=496, y=99, z=2352} but found not block entity block Block{minecraft:end_stone} at location
[Server thread/WARN]: Tried to load a block entity for block Block{minecraft:end_stone} but failed at location class_2338{x=496, y=99, z=2352}
[Server thread/WARN]: Tried to load a DUMMY block entity @ class_2338{x=1795, y=-65, z=2675} but found not block entity block Block{minecraft:air} at location
[Server thread/WARN]: Tried to load a block entity for block Block{minecraft:air} but failed at location class_2338{x=1795, y=-65, z=2675}
[Server thread/WARN]: Tried to load a DUMMY block entity @ class_2338{x=1800, y=-65, z=2685} but found not block entity block Block{minecraft:air} at location
[Server thread/WARN]: Tried to load a block entity for block Block{minecraft:air} but failed at location class_2338{x=1800, y=-65, z=2685}
[Server thread/WARN]: Tried to load a DUMMY block entity @ class_2338{x=1805, y=-65, z=2675} but found not block entity block Block{minecraft:air} at location
[Server thread/WARN]: Tried to load a block entity for block Block{minecraft:air} but failed at location class_2338{x=1805, y=-65, z=2675}
[Server thread/WARN]: Tried to load a DUMMY block entity @ class_2338{x=1795, y=-65, z=2683} but found not block entity block Block{minecraft:air} at location
[Server thread/WARN]: Tried to load a block entity for block Block{minecraft:air} but failed at location class_2338{x=1795, y=-65, z=2683}
[Server thread/WARN]: Tried to load a DUMMY block entity @ class_2338{x=1800, y=-65, z=2673} but found not block entity block Block{minecraft:air} at location
[Server thread/WARN]: Tried to load a block entity for block Block{minecraft:air} but failed at location class_2338{x=1800, y=-65, z=2673}
[Server thread/WARN]: Tried to load a DUMMY block entity @ class_2338{x=1805, y=-65, z=2683} but found not block entity block Block{minecraft:air} at location
[Server thread/WARN]: Tried to load a block entity for block Block{minecraft:air} but failed at location class_2338{x=1805, y=-65, z=2683}
[Server thread/ERROR]: Failed to create block entity minecraft:banner
java.lang.ClassCastException: class ru.betterend.blocks.MossyGlowshroomCapBlock cannot be cast to class net.minecraft.class_2185 (ru.betterend.blocks.MossyGlowshroomCapBlock and net.minecraft.class_2185 are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @66982506)
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.61) ~[?:?]
	at net.minecraft.block.entity.BannerBlockEntity.<init>(BannerBlockEntity:43) ~[?:?]
	at net.minecraft.block.entity.BlockEntityType.instantiate(BlockEntityType:84) ~[?:?]
	at net.minecraft.block.entity.BlockEntity.method_17899(BlockEntity:79) ~[?:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraft.block.entity.BlockEntity.createFromNbt(BlockEntity:77) ~[?:?]
	at net.minecraft.world.chunk.WorldChunk.loadBlockEntity(WorldChunk:714) ~[?:?]
	at net.minecraft.world.chunk.WorldChunk.getBlockEntity(WorldChunk:376) ~[?:?]
	at net.minecraft.world.chunk.WorldChunk.getBlockEntity(WorldChunk:367) ~[?:?]
	at net.minecraft.world.chunk.WorldChunk.getPackedBlockEntityNbt(WorldChunk:447) ~[?:?]
	at net.minecraft.world.ChunkSerializer.serialize(ChunkSerializer:285) ~[?:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.save(ThreadedAnvilChunkStorage:686) ~[?:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_18843(ThreadedAnvilChunkStorage:444) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.unloadChunks(ThreadedAnvilChunkStorage:425) ~[?:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.tick(ThreadedAnvilChunkStorage:402) ~[?:?]
	at net.minecraft.server.world.ServerChunkManager.tick(ServerChunkManager:326) ~[?:?]
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:372) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:891) ~[intermediary-server.jar:?]
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:335) ~[?:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:831) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:697) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[Server thread/WARN]: Skipping BlockEntity with id minecraft:banner
[Server thread/WARN]: Tried to load a block entity for block Block{betterend:mossy_glowshroom_cap}[transition=false] but failed at location class_2338{x=-3794, y=170, z=2311}
```
**Isolated test log** (when error as replicated): https://pastebin.com/JPUtgshd
**Original modpack log** (when error as detected): https://pastebin.com/KmG1KzC9

**Comment by paulevsGitch** [comment]
Looks like a mod conflict, probably one of mods tries to cast block to incorrect class

Due to this line looks like block is forced to be loaded as having TileEntity, but this block don't have it
> Tried to load a block entity for block Block{betterend:mossy_glowshroom_cap}

You can try to find conflicting mod by disabling mods one by one or half by half

**Comment by davidalb97** [comment]
I can confirm that I could replicate the issue with only bclib, better nether, fabric-api and blame (only used as debug to find any possible structure issue).

I updated the initial description with replication steps and the new test result log.

**Comment by paulevsGitch** [comment]
As fix was implemented on BClib side I think this can be closed

**Comment by davidalb97** [comment]
I can confirm this issue still exists.
The previously referenced issue [#43](https://github.com/paulevsGitch/BCLib/issues/43) on BCLib was not related to this one. 
Error: https://pastebin.com/T6aNCgua

**Comment by paulevsGitch** [comment]
I can see there are some other entities that tries to spawn as vanila blocks:
> Tried to load a DUMMY block entity @ class_2338{x=-1625, y=61, z=2054} but found not block entity block Block{minecraft:end_stone} at location
[21:32:48] [Server thread/WARN]: Tried to load a block entity for block Block{minecraft:end_stone} but failed at location class_2338{x=-1625, y=61, z=2054}
[21:53:09] [Server thread/WARN]: Tried to load a DUMMY block entity @ class_2338{x=855, y=80, z=2374} but found not block entity block Block{minecraft:end_stone} at location
[21:53:09] [Server thread/WARN]: Tried to load a block entity for block Block{minecraft:end_stone} but failed at location class_2338{x=855, y=80, z=2374}

I don't know what can cause this issue, but BE & BClib use same structure system as all other mods. Looks like this is an issue of multithread chuk generation - structure generates in one thread, in the second it get replaced by another structure, and the first structure have block entities like chests. Can you recreate this issue with only teleporting to this location?

**Comment by davidalb97** [comment]
I'll try it tomorrow afternoon, however, forgot to mention that the issue does no occur on the nether with only BetterNether + BCLib installed.
I can only replicate this issue on end pregeneration with BCLib and BetterEnd.

**Comment by davidalb97** [comment]
Teleporting to the already pregenerated world shows no errors or warnings: https://pastebin.com/KJPicLnQ
Teleporting to a new world with the same seed but without pregeneration shows one of the two warnings but no error: https://pastebin.com/CqXiaWCh

When teleporting to a new world with the same seed, only one of the tp commands caused a warning, however no error stacktrace was displayed.
```
[Server thread/WARN]: Tried to load a DUMMY block entity @ class_2338{x=-1625, y=65, z=2029} but found not block entity block Block{minecraft:end_stone} at location
[Server thread/WARN]: Tried to load a block entity for block Block{minecraft:end_stone} but failed at location class_2338{x=-1625, y=65, z=2029}
```
