### ISSUE TITLE
java.lang.IllegalStateException: No renderer registered for betterend:dragonfly

### ISSUE THREAD

**Issue by Pedrzi** [paulevsGitch/BetterEnd#363]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 12/5/21 7:23 PM
Description: Initializing game

java.lang.IllegalStateException: No renderer registered for betterend:dragonfly
	at net.minecraft.class_898.<init>(class_898.java:204)
	at net.minecraft.class_310.<init>(class_310.java:527)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_898.<init>(class_898.java:204)
	at net.minecraft.class_310.<init>(class_310.java:527)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1059369944 bytes (1010 MB) / 1518862336 bytes (1448 MB) up to 7635730432 bytes (7282 MB)
	CPUs: 4
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8192m -Xms256m
	Suspected Mods: Fabric Loader (fabricloader), Minecraft (minecraft)
	Fabric Mods: 
		amecsapi: Amecs API 1.1.4+mc1.16.5
		appleskin: AppleSkin mc1.16.4-2.2.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		backslot: BackSlot 1.1.11
		bclib: BCLib 0.1.45
		bettercaves: YUNG's Better Caves 1.16.5-1.2
		betterdungeons: YUNG's Better Dungeons 1.16.5-1.0.1
		betterend: Better End 0.9.8.5-pre
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0.2
		betternether: Better Nether 5.0.7
		betterstrongholds: YUNG's Better Strongholds 1.16.5-1.1.1
		biom4st3r_repackaged_expressions: expj4_repackaged 0.1.0
		blame: Blame 1.16.5-3.2.0-fabric
		cardinal-components-base: Cardinal Components API (base) 2.8.2
		cardinal-components-entity: Cardinal Components API (entities) 2.8.2
		cavebiomes: Cave Biomes 0.6.2
		cleancut: CleanCut mc1.16-2.1-fabric
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.12.41
		collective-fabric: Collective (Fabric) 3.13
		darkness: True Darkness 1.6.58
		dehydration: Dehydration 1.1.4
		dual_riders: DualRiders 1.0.5
		dualwielding: Dual Wielding 1.0.2
		dungeons_arise: When Dungeons Arise 1.16.5-2.1.47-fabric
		dungeonsmod: Dungeons Mod Lite 1.16.5-1.0.12
		enchant_giver: Enchant Giver 1.0.3
		enhancedcelestials: Enhanced Celestials 2.0.6
		extraorigins: Extra Origins 1.16.5-12
		fabric: Fabric API 0.42.0+1.16
		fabric-api-base: Fabric API Base 0.4.0+3cc0f0907d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+3cc0f0907d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.13+3cc0f0907d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+3cc0f0907d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+3cc0f0907d
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+3cc0f0907d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+3cc0f0907d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.5+3cc0f0907d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.4+3cc0f0907d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.8+3cc0f0907d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.4+3cc0f0907d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.5+3cc0f0907d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+3cc0f0907d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+3cc0f0907d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.2+3cc0f0907d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+3cc0f0907d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+3cc0f0907d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+3cc0f0907d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.2+3cc0f0907d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.3+3cc0f0907d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.4+3cc0f0907d
		fabric-models-v0: Fabric Models (v0) 0.3.1+3cc0f0907d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.5+3cc0f0907d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.9+3cc0f0907d
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+3cc0f0907d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.6+3cc0f0907d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+3cc0f0907d
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+3cc0f0907d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.6+3cc0f0907d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+3cc0f0907d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.5+3cc0f0907d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.1+3cc0f0907d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+3cc0f0907d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.15+3cc0f0907d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.3+3cc0f0907d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.1+3cc0f0907d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+3cc0f0907d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.1+3cc0f0907d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.6+3cc0f0907d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+3cc0f0907d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.2+3cc0f0907d
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+3cc0f0907d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.8+3cc0f0907d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.0+3cc0f0907d
		fabricloader: Fabric Loader 0.12.8
		fallflyinglib: FallFlyingLib 1.1.0
		farmersdelight: Farmer's Delight 1.16.5-0.0.7
		fiber: fiber 0.23.0-2
		geckolib3: Geckolib 3.0.59
		graveyard: The Graveyard 1.1
		indium: Indium 1.0.0+mc1.16.5
		java: Java HotSpot(TM) 64-Bit Server VM 8
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		krypton: Krypton 0.1.2
		lambdynlights: LambDynamicLights 1.3.4+1.16
		lazydfu: LazyDFU 0.1.2
		lithium: Lithium 0.6.6
		mcda: MC Dungeons Armors 1.5.0
		mcdw: MC Dungeons Weapons 3.2.0
		mimics: Mimics 0.1.4
		minecraft: Minecraft 1.16.5
		moborigins: Mob Origins 1.4.0
		modmenu: Mod Menu 1.16.22
		moenchant_lib: Mo'Enchantment Library 0.1.0
		moenchantments: Mo'Enchantments 1.15.2
		mostructures: Mo' Structures 1.2.0-1.16.5
		mythic-mounts: Mythic Mounts 1.16.5-3.0
		notenoughcrashes: Not Enough Crashes 4.1.2+1.16.5
		offlineskins: OfflineSkins 1.16.5-v1-fabric
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		omega-config: OmegaConfig 1.0.4
		org_aeonbits_owner_owner: owner 1.0.12
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		origins: Origins 0.7.3
		origins-classes: Origins: Classes 1.1.1
		particle_emitter_biom4st3r: Particle Emitters LIB 0.1.0
		pehkui: Pehkui 3.0.0+1.14.4-1.18
		playerabilitylib: Pal 1.2.1
		playerex: PlayerEx 2.0.5
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		roughlyenoughitems: Roughly Enough Items 5.12.248
		roughlyenoughitems-api: REI (API) 5.12.248
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.12.248
		roughlyenoughitems-runtime: REI (Runtime) 5.12.248
		rpgdifficulty: Rpg Difficulty 1.0.4
		runelic: Runelic 1.0.2
		simple_backpack: SimpleBackpack 1.0.38
		smoothboot: Smooth Boot 1.16.5-1.6.0
		sodium: Sodium 0.2.0+build.4
		spruceui: SpruceUI 2.0.4+1.16
		starlight: Starlight fabric-1.0.0-RC2-82ae5ca
		starterkit-fabric: Starter Kit (Fabric) 3.1
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		tooltipfix: ToolTip Fix 1.0.2-1.16
		villagespawnpoint-fabric: Village Spawn Point (Fabric) 1.8
		voicechat: Simple Voice Chat 1.16.5-1.10.0
		waila: Hwyla 1.9.22
		walljump: Wall-Jump! 1.3.3+1.16.1
		waystones: Waystones 2.0.1
		xaerominimap: Xaero's Minimap 21.22.3
		xaeroworldmap: Xaero's World Map 1.18.4
		yungsapi: YUNG's API 1.16.5-Fabric-9
	Launched Version: fabric-loader-0.12.8-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon(TM) Vega 8 Graphics GL version 4.6.13596 Compatibility Profile Context 20.10.20 27.20.1020.1, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 4x AMD Ryzen 3 3200G with Radeon Vega Graphics

**Comment by Pedrzi** [comment]
pehkui 3.0.0 was the problem
