### ISSUE TITLE
[1.18.1] REI shows "not yet fully initialized" with BetterEnd installed

### ISSUE THREAD

**Issue by ypf791** [paulevsGitch/BetterEnd#409]
[Environment]

Java 17
Minecraft 1.18.1
Fabric 0.45.2
BCLib 1.2.3
BetterEnd 1.0.0

For more details, please refer to the logs.

[Symptom]

![image](https://user-images.githubusercontent.com/4142799/149658728-b53c75c5-ca89-464c-a3a7-0bd3c4b8b5bf.png)

[Logs]

[better-end-with-rei-issue.log](https://github.com/paulevsGitch/BetterEnd/files/7876887/better-end-with-rei-issue.log)

[19:49:20] [Render thread/WARN]: Suppressing Reload Plugins of stage START
[19:49:20] [Render thread/FATAL]: Error executing task on Client
java.lang.IllegalArgumentException: Multiple entries with same key: betterend:end_berry=net.minecraft.class_3861@69225b97 and betterend:end_berry=net.minecraft.class_3862@411511b0
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:376) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:370) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:153) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:115) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.buildOrThrow(ImmutableMap.java:574) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:538) ~[guava-31.0.1-jre.jar:?]

**Comment by paulevsGitch** [comment]
Update your BCLib

**Comment by ypf791** [comment]
BCLib 1.2.4 saves me! Thanks a lot!
