### ISSUE TITLE
Crashing Fabric 1.18.1 Better End and Better Nether

### ISSUE THREAD

**Issue by DJTobi1Kenobi** [paulevsGitch/BetterEnd#416]
Crashing on Startup with the following error:

[00:46:41] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.12
[00:46:41] [ForkJoinPool-1-worker-3/WARN]: The mod "extraalchemy" contains invalid entries in its mod json:
- Invalid entry in person "contribution" at line 19 column 21
[00:46:41] [main/WARN]: Warnings were found!
 - Mod 'Sodium Extra' (sodium-extra) 0.3.8 recommends version 1.2.3 or later of reeses-sodium-options, which is missing!
	 - You should install version 1.2.3 or later of reeses-sodium-options for the optimal experience.
[00:46:41] [main/INFO]: Loading 202 mods:
	- accurateblockplacement 1.0.11
	- adorn 3.2.0+1.18.1
	- advanced_runtime_resource_pack 0.2.9 via carrier
	- adventurez 1.4.7
	- afkpeace 4.7.0
	- appleskin mc1.18-2.2.0
	- aqupdcaracal 1.18-1.3.5.1
	- arcanus 1.25
	- architectury 3.4.9
	- attributefix 1.0.3
	- axesareweapons 1.5.1
	- basicshields 1.2.1-1.18.1
	- bclib 1.2.5
	- betterend 1.0.1
	- betternether 6.0.8
	- blue_endless_jankson 1.2.1 via jankson
	- bowinfinityfix rv11
	- byg 1.3.5.6
	- caffeineconfig 1.0.0 via sodium-extra
	- campanion 3.0.2
	- cardinal-components-base 4.0.1 via polymorph
	- cardinal-components-block 4.0.1 via polymorph
	- cardinal-components-entity 4.0.1 via polymorph
	- cardinal-components-item 4.0.1 via polymorph
	- carrier 1.9.0
	- cleancut 1.18-4.0-fabric
	- cloth-api 3.1.61
	- cloth-basic-math 0.6.0 via cloth-api
	- cloth-client-events-v0 3.1.61 via cloth-api
	- cloth-common-events-v1 3.1.61 via cloth-api
	- cloth-config 6.1.48
	- cloth-config-lite 2.0.6 via omega-config-gui
	- cloth-datagen-api-v1 3.1.61 via cloth-api
	- cloth-scissors-api-v1 3.1.61 via cloth-api
	- cloth-utils-v1 3.1.61 via cloth-api
	- com_electronwill_night-config_core 3.6.4 via terrablender
	- com_electronwill_night-config_toml 3.6.4 via terrablender
	- com_moandjiezana_toml_toml4j 0.7.2 via dynamicfps
	- continuity 1.0.3+1.18
	- cullleaves 2.3.2
	- damagetilt 1.18-fabric-0.1.2
	- dual_riders 1.0.5
	- dungeons_arise 2.1.49b-fabric
	- dynamicfps 2.1.0
	- editsign 2.2.7
	- elytratrinket 3.0.0-1.18.1
	- enchant_giver 1.1.0 via mcdw
	- enchdesc 9.0.11
	- enhanced_attack_indicator 1.0.2+1.18
	- entityculling 1.3.3
	- expanded_trident_enchanting 1.0.3
	- expanded_weapon_enchanting 1.0.2
	- expandedstorage 7.3.4
	- extraalchemy 1.7.0
	- ezpas 2.0.1
	- fabric 0.46.2+1.18
	- fabric-api-base 0.4.1+b4f4f6cd3a via fabric
	- fabric-api-lookup-api-v1 1.5.1+17be577f3a via fabric
	- fabric-biome-api-v1 6.0.1+ded849a93a via fabric
	- fabric-blockrenderlayer-v1 1.1.9+3ac43d953a via fabric
	- fabric-command-api-v1 1.1.6+3ac43d953a via fabric
	- fabric-commands-v0 0.2.5+b4f4f6cd3a via fabric
	- fabric-containers-v0 0.1.18+d154e2c63a via fabric
	- fabric-content-registries-v0 0.4.6+6f53a73d3a via fabric
	- fabric-crash-report-info-v1 0.1.8+3ac43d953a via fabric
	- fabric-dimensions-v1 2.1.9+a1d9bbf53a via fabric
	- fabric-entity-events-v1 1.4.5+6b21378a3a via fabric
	- fabric-events-interaction-v0 0.4.16+bfa23f173a via fabric
	- fabric-events-lifecycle-v0 0.2.7+b4f4f6cd3a via fabric
	- fabric-game-rule-api-v1 1.0.10+3ac43d953a via fabric
	- fabric-item-api-v1 1.3.0+691a79b53a via fabric
	- fabric-item-groups-v0 0.3.4+3ac43d953a via fabric
	- fabric-key-binding-api-v1 1.0.8+c8aba2f33a via fabric
	- fabric-keybindings-v0 0.2.6+b4f4f6cd3a via fabric
	- fabric-language-kotlin 1.7.1+kotlin.1.6.10
	- fabric-lifecycle-events-v1 1.4.11+e66b59e93a via fabric
	- fabric-loot-tables-v1 1.0.8+3ac43d953a via fabric
	- fabric-mining-level-api-v1 1.0.4+3ac43d953a via fabric
	- fabric-mining-levels-v0 0.1.9+b4f4f6cd3a via fabric
	- fabric-models-v0 0.3.3+3ac43d953a via fabric
	- fabric-networking-api-v1 1.0.18+3ac43d953a via fabric
	- fabric-networking-v0 0.3.5+b4f4f6cd3a via fabric
	- fabric-object-builder-api-v1 1.11.2+3b82842e3a via fabric
	- fabric-object-builders-v0 0.7.10+3ac43d953a via fabric
	- fabric-particles-v1 0.2.9+526dc1ac3a via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via universal-graves
	- fabric-registry-sync-v0 0.9.0+befed49e3a via fabric
	- fabric-renderer-api-v1 0.4.10+b0b66fc33a via fabric
	- fabric-renderer-indigo 0.4.13+b0b66fc33a via fabric
	- fabric-renderer-registries-v1 3.2.8+b4f4f6cd3a via fabric
	- fabric-rendering-data-attachment-v1 0.3.4+7242e9d73a via fabric
	- fabric-rendering-fluids-v1 0.1.18+3ac43d953a via fabric
	- fabric-rendering-v0 1.1.10+b4f4f6cd3a via fabric
	- fabric-rendering-v1 1.10.4+e66b59e93a via fabric
	- fabric-resource-conditions-api-v1 1.0.1+13eda0653a via fabric
	- fabric-resource-loader-v0 0.4.12+e66b59e93a via fabric
	- fabric-screen-api-v1 1.0.7+3ac43d953a via fabric
	- fabric-screen-handler-api-v1 1.1.11+3ac43d953a via fabric
	- fabric-structure-api-v1 2.1.1+0a73a6c23a via fabric
	- fabric-tag-extensions-v0 1.2.6+3ac43d953a via fabric
	- fabric-textures-v0 1.0.9+3ac43d953a via fabric
	- fabric-tool-attribute-api-v1 1.3.6+fb3b57b43a via fabric
	- fabric-transfer-api-v1 1.5.7+b4f4f6cd3a via fabric
	- fabricloader 0.12.12
	- fabricshieldlib 1.4.5-1.18
	- fake-player-api 0.3.0 via indrev
	- fallingtree 3.1.0
	- fatxporbs 2.0.0
	- fiber 0.23.0-2 via patchouli
	- flytre-lib-base 1.3.0 via flytre_lib
	- flytre-lib-compat 1.0.0 via flytre_lib
	- flytre-lib-config 1.1.0 via flytre_lib
	- flytre-lib-event 1.0.1 via flytre_lib
	- flytre-lib-gui 1.0.0 via flytre_lib
	- flytre-lib-storage 2.3.2 via flytre_lib
	- flytre_lib 1.4.4
	- hh 1.3.12 via limitless
	- hologram-api 0.2.1+1.18-pre5 via universal-graves
	- imm_ptl_core 1.2.4 via immersive_portals
	- immersive_portals 1.2.4
	- indium 1.0.2-alpha2+mc1.18.1
	- indrev 1.13.6-BETA
	- inspecio 1.2.1+1.18
	- iris 1.2.0-pre
	- jankson 4.0.0+j1.2.0 via adorn
	- java 17
	- jumpoverfences 1.16-0.0.3
	- kbootstrap 0.2.1 via hh
	- kirin 1.10.0-beta.2 via presencefootsteps
	- libblockattributes_core 0.10.0 via indrev
	- libblockattributes_fluids 0.10.0 via indrev
	- libblockattributes_items 0.10.0 via indrev
	- libgui 5.1.0+1.18 via rpgstats
	- libninepatch 1.1.0 via libgui
	- lightoverlay 6.0.4
	- limitless 1.6.1
	- lithium 0.7.7
	- lovely_snails 1.0.3+1.18
	- magna 1.7.0-1.18-pre1 via indrev
	- mcda 1.9.0
	- mcdar 1.4.3-1.18
	- mcdw 4.0.2
	- midnightlib 0.2.9 via cullleaves
	- minecraft 1.18.1
	- modmenu 3.0.1
	- morevillagers-fabric 3.1.1-SNAPSHOT
	- net_auoeke_extensions_asm-tree 0.37.1 via hh
	- net_auoeke_extensions_extensions 0.37.1 via hh
	- net_auoeke_reflect 4.2.0 via limitless
	- net_gudenau_lib_unsafe 1.6.1 via hh
	- ninjaphenix_container_lib 1.2.10
	- notenoughcrashes 4.1.4+1.18.1
	- omega-config 1.2.2-1.18.1 via afkpeace
	- omega-config-gui 1.2.2-1.18.1 via afkpeace
	- org_anarres_jcpp 1.4.14 via iris
	- org_jetbrains_kotlin_kotlin-reflect 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.1 via fabric-language-kotlin
	- org_joml_joml 1.10.2 via sodium
	- org_slf4j_slf4j-api 1.7.12 via iris
	- oxidized 1.5.2
	- packet_tweaker 0.2.0+1.18-pre1 via polymer
	- patchouli 1.18.1-64-FABRIC
	- phosphor 0.8.1
	- pinglist 1.3.3
	- placeholder-api 1.1.3+1.17.1 via universal-graves
	- polymer 0.2.0-beta.15+1.18.1 via universal-graves
	- polymer-legacy 0.1.9+0.2.0-beta.15+1.18.1 via polymer
	- polymorph 0.0.19-1.18.1
	- presencefootsteps 1.4.0
	- q_misc_util 1.2.4 via immersive_portals
	- reach-entity-attributes 2.1.1 via campanion
	- reroll 1.4.0-1.18.1
	- roughlyenoughitems 7.1.390
	- rpgstats 4.3.4+1.18.1
	- seedfix 1.0.0 via terralith
	- server_translations_api 1.4.8+1.18-pre1 via universal-graves
	- sgui 1.0.0-rc6+1.18-pre5 via universal-graves
	- skyvillages 1.0.1-1.18.1-fabric
	- sodium 0.4.0-alpha6+build.14
	- sodium-extra 0.3.8
	- statuseffecttimer 1.1.0+1.18.1
	- step-height-entity-attribute 1.0.0 via indrev
	- stoneholm 1.4.1
	- team_reborn_energy 2.0.0-beta1 via indrev
	- terrablender 1.1.0.72
	- terralith 2.0.12
	- trinkets 3.1.0
	- universal-graves 2.0.0-beta.4.1+1.18.1
	- voidtotem 1.18.1-1.1.0
	- waystones 2.4.0
	- whereisit 1.14.7
	- wthit 4.4.1
	- xaerominimap 21.23.1
	- xaeroworldmap 1.19.1
	- xp_storage 1.4.3+1.18
[00:46:41] [main/WARN]: Mod `appleskin` (mc1.18-2.2.0) does not respect SemVer - comparison support is limited.
[00:46:41] [main/WARN]: Mod `bowinfinityfix` (rv11) does not respect SemVer - comparison support is limited.
[00:46:41] [main/WARN]: Mod `byg` (1.3.5.6) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
[00:46:41] [main/WARN]: Mod `dungeons_arise` (2.1.49b-fabric) does not respect SemVer - comparison support is limited.
[00:46:41] [main/WARN]: Mod `polymer-legacy` (0.1.9+0.2.0-beta.15+1.18.1) does not respect SemVer - comparison support is limited.
[00:46:41] [main/WARN]: Mod `terrablender` (1.1.0.72) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
[00:46:42] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/Tobi/Downloads/Minecraft/mmc-stable-win32/MultiMC/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=CLIENT
[00:46:42] [main/INFO]: Compatibility level set to JAVA_17
[00:46:42] [main/WARN]: Reference map 'ezpas-refmap.json' for ezpas.mixins.json could not be read. If this is a development environment you can ignore this message
[00:46:42] [main/WARN]: Reference map 'flytre-lib-compat-refmap.json' for flytre-lib-compat.mixins.json could not be read. If this is a development environment you can ignore this message
[00:46:42] [main/INFO]: Loaded configuration file for Lithium: 88 options available, 1 override(s) found
[00:46:43] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[00:46:43] [main/INFO]: Loaded configuration file for Sodium Extra: 17 options available, 0 override(s) found
[00:46:43] [main/WARN]: Error loading class: grondag/canvas/terrain/region/input/InputRegion (java.lang.ClassNotFoundException: grondag/canvas/terrain/region/input/InputRegion)
[00:46:43] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [immersive_portals]) disables it and children
[00:46:43] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[00:46:43] [main/WARN]: Error loading class: me/flashyreese/mods/reeses_sodium_options/client/gui/SodiumVideoOptionsScreen (java.lang.ClassNotFoundException: me/flashyreese/mods/reeses_sodium_options/client/gui/SodiumVideoOptionsScreen)
[00:46:43] [main/INFO]: I used the json to destroy the json
[00:46:43] [main/INFO]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[00:46:44] [main/INFO]: sodium-extra.mixins.json:features.gui.MinecraftClientAccessor->@Accessor[FIELD_GETTER]::getCurrentFPS()I should be static as its target is
[00:46:46] [main/WARN]: Injection warning: LVT in net/minecraft/class_2404::method_10316(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;)Z has incompatible changes at opcode 120 in callback betternether.mixins.common.json:LiquidBlockMixin->@Inject::bn_shouldSpreadLiquid(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;ZLcom/google/common/collect/UnmodifiableIterator;Lnet/minecraft/class_2350;Lnet/minecraft/class_2338;Lnet/minecraft/class_2248;)V from mod betternether.
 Expected: [Z, Lcom/google/common/collect/UnmodifiableIterator;, Lnet/minecraft/class_2350;, Lnet/minecraft/class_2338;, Lnet/minecraft/class_2248;]
    Found: [Z, Lcom/google/common/collect/UnmodifiableIterator;, Lnet/minecraft/class_2350;, Lnet/minecraft/class_2338;]
Available: [Z, Lcom/google/common/collect/UnmodifiableIterator;, Lnet/minecraft/class_2350;, Lnet/minecraft/class_2338;]
[00:46:46] [main/WARN]: Method overwrite conflict for method_9522 in sodium.mixins.json:features.render_layer.leaves.MixinLeavesBlock, previously written by eu.midnightdust.cullleaves.mixin.MixinLeavesBlock. Skipping method.
[00:46:47] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$bia000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[00:46:50] [main/INFO]: [bclib] Added Config betternether.main to auto sync (file hash)
[00:46:50] [main/INFO]: [bclib] Added Config betternether.generator to auto sync (file hash)
[00:46:50] [main/INFO]: [bclib] Added Config betternether.blocks to auto sync (file hash)
[00:46:50] [main/INFO]: [bclib] Added Config betternether.items to auto sync (file hash)
[00:46:50] [main/INFO]: [bclib] Added Config betternether.mobs to auto sync (file hash)
[00:46:50] [main/INFO]: [bclib] Added Config betternether.recipes to auto sync (file hash)
[00:46:50] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchFieldError: ITEM_IRON_INGOTS
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:610) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoSuchFieldError: ITEM_IRON_INGOTS
	at paulevs.betternether.registry.NetherItems.<clinit>(NetherItems.java:63) ~[better-nether-6.0.8.jar:?]
	at paulevs.betternether.blocks.complex.NetherWoodenMaterial.init(NetherWoodenMaterial.java:63) ~[better-nether-6.0.8.jar:?]
	at paulevs.betternether.blocks.complex.RoofMaterial.init(RoofMaterial.java:25) ~[better-nether-6.0.8.jar:?]
	at paulevs.betternether.blocks.complex.StalagnateMaterial.init(StalagnateMaterial.java:28) ~[better-nether-6.0.8.jar:?]
	at paulevs.betternether.registry.NetherBlocks.<clinit>(NetherBlocks.java:143) ~[better-nether-6.0.8.jar:?]
	at paulevs.betternether.entity.EntityFirefly.<clinit>(EntityFirefly.java:528) ~[better-nether-6.0.8.jar:?]
	at paulevs.betternether.registry.NetherEntities.<clinit>(NetherEntities.java:65) ~[better-nether-6.0.8.jar:?]
	at net.minecraft.entity.attribute.DefaultAttributeRegistry.handler$zlo000$hasDefinition(DefaultAttributeRegistry:1026) ~[?:?]
	at net.minecraft.entity.attribute.DefaultAttributeRegistry.hasDefinitionFor(DefaultAttributeRegistry) ~[?:?]
	at net.minecraft.entity.attribute.DefaultAttributeRegistry.method_26876(DefaultAttributeRegistry:168) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.entity.attribute.DefaultAttributeRegistry.checkMissing(DefaultAttributeRegistry:170) ~[?:?]
	at net.minecraft.Bootstrap.logMissing(Bootstrap:137) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:156) ~[minecraft-1.18.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 10 more

**Comment by FirstMegaGame4** [comment]
Use the last version off BetterNether.

**Comment by DJTobi1Kenobi** [comment]
I feel like a fool! thank you very much for helping me sort this. I'll be usre to triple check next time before opening a bug report.
