### ISSUE TITLE
player disconnect + massive lag, when leaving end through the custom portal,

### ISSUE THREAD

**Issue by aidansstuff** [paulevsGitch/BetterEnd#487]
hi 
I am the server admin for our friend's group server, and my friend is the one who made the mod pack, so I don't know the exact name for it, but we had an issue leaving the end using the portals that you can reactivate on the outer end islands. It disconnected a friend and me when we went in, and when we tried rejoining, it caused enough lag to shut the server down.
`[19:57:35] [Server thread/INFO]: [bclib] Checking class_2339{x=-1745, y=49, z=-416} for Portal
[19:57:35] [Server thread/WARN]: Failed to handle packet for /###.###.###.###:#### (censored IP)
net.minecraft.class_148: Colliding entity with block
	at net.minecraft.class_3222.method_14226(class_3222.java:551) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_18784(class_3244.java:268) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:248) ~[server-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'java.util.Optional org.betterx.bclib.api.v2.poi.BCLPoiType.findClosest(net.minecraft.class_3218, net.minecraft.class_2338, int)'
	at org.betterx.betterend.rituals.EternalRitual.findClosestPoi(EternalRitual.java:783) ~[better-end-2.1.3.jar:?]
	at org.betterx.betterend.rituals.EternalRitual.findBlockPos(EternalRitual.java:733) ~[better-end-2.1.3.jar:?]
	at org.betterx.betterend.blocks.EndPortalBlock.findExitPos(EndPortalBlock.java:169) ~[better-end-2.1.3.jar:?]
	at org.betterx.betterend.blocks.EndPortalBlock.method_9548(EndPortalBlock.java:115) ~[better-end-2.1.3.jar:?]
	at net.minecraft.class_4970$class_4971.method_26178(class_4970.java:952) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.method_5852(class_1297.java:1059) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.method_36974(class_1297.java:783) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.method_5784(class_1297.java:752) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_26318(class_1309.java:2282) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_6091(class_1309.java:2227) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_6091(class_1657.java:1638) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_6007(class_1309.java:2680) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_6007(class_1657.java:570) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2385) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_5773(class_1657.java:284) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_14226(class_3222.java:487) ~[server-intermediary.jar:?]
	... 9 more
[19:57:35] [Server thread/INFO]: HexManiacZoroark lost connection: Internal server error
[19:57:35] [Server thread/INFO]: HexManiacZoroark left the game
[19:57:37] [Server thread/INFO]: [bclib] Checking class_2339{x=-1745, y=49, z=-416} for Portal
[19:57:37] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2828$class_2830@1ccad698, suppressing error
net.minecraft.class_148: Colliding entity with block
	at net.minecraft.class_1297.method_36974(class_1297.java:790) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.method_5784(class_1297.java:752) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_12063(class_3244.java:965) ~[server-intermediary.jar:?]
	at net.minecraft.class_2828.method_12272(class_2828.java:114) ~[server-intermediary.jar:?]
	at net.minecraft.class_2828$class_2830.method_11054(class_2828.java:16) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'java.util.Optional org.betterx.bclib.api.v2.poi.BCLPoiType.findClosest(net.minecraft.class_3218, net.minecraft.class_2338, int)'
	at org.betterx.betterend.rituals.EternalRitual.findClosestPoi(EternalRitual.java:783) ~[better-end-2.1.3.jar:?]
	at org.betterx.betterend.rituals.EternalRitual.findBlockPos(EternalRitual.java:733) ~[better-end-2.1.3.jar:?]
	at org.betterx.betterend.blocks.EndPortalBlock.findExitPos(EndPortalBlock.java:169) ~[better-end-2.1.3.jar:?]
	at org.betterx.betterend.blocks.EndPortalBlock.method_9548(EndPortalBlock.java:115) ~[better-end-2.1.3.jar:?]
	at net.minecraft.class_4970$class_4971.method_26178(class_4970.java:952) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.method_5852(class_1297.java:1059) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.method_36974(class_1297.java:783) ~[server-intermediary.jar:?]
	... 18 more
[19:57:38] [Server thread/INFO]: [bclib] Checking class_2339{x=-1745, y=49, z=-416} for Portal
[19:57:38] [Server thread/WARN]: Failed to handle packet for /192.168.1.132:14908
net.minecraft.class_148: Colliding entity with block
	at net.minecraft.class_3222.method_14226(class_3222.java:551) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_18784(class_3244.java:268) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:248) ~[server-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'java.util.Optional org.betterx.bclib.api.v2.poi.BCLPoiType.findClosest(net.minecraft.class_3218, net.minecraft.class_2338, int)'
	at org.betterx.betterend.rituals.EternalRitual.findClosestPoi(EternalRitual.java:783) ~[better-end-2.1.3.jar:?]
	at org.betterx.betterend.rituals.EternalRitual.findBlockPos(EternalRitual.java:733) ~[better-end-2.1.3.jar:?]
	at org.betterx.betterend.blocks.EndPortalBlock.findExitPos(EndPortalBlock.java:169) ~[better-end-2.1.3.jar:?]
	at org.betterx.betterend.blocks.EndPortalBlock.method_9548(EndPortalBlock.java:115) ~[better-end-2.1.3.jar:?]
	at net.minecraft.class_4970$class_4971.method_26178(class_4970.java:952) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.method_5852(class_1297.java:1059) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.method_36974(class_1297.java:783) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.method_5784(class_1297.java:752) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_26318(class_1309.java:2282) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_6091(class_1309.java:2227) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_6091(class_1657.java:1638) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_6007(class_1309.java:2680) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_6007(class_1657.java:570) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2385) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_5773(class_1657.java:284) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_14226(class_3222.java:487) ~[server-intermediary.jar:?]
	... 9 more
[19:57:38] [Server thread/INFO]: GroenNinja lost connection: Internal server error
[19:57:38] [Server thread/INFO]: GroenNinja left the game
`
[crash-2023-02-14_19.58.18-server.txt](https://github.com/paulevsGitch/BetterEnd/files/10738025/crash-2023-02-14_19.58.18-server.txt)

**Comment by paulevsGitch** [comment]
Hi, please don't use old repo for issues, use only [the new one](https://github.com/quiqueck/BetterEnd)
